import 'package:get/get.dart';

import '../translation_key.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      greetingWord:"Hello",
      requiredFiled:"This field is required",
      invalidEmail:"This e-mail is invalid",
      invalidPassword:"This password is invalid",
      tryAgain:"Please try again later",
      noInternet:"There's no internet connection",
      openInternet:"Please open your internet and try again",

      error:"There's error happen please try again later",
      phoneNumberError:"This phone number is not valid",
      invalidReTypePassword:"passwords does not match",
      enterPasswordFirst:"You must enter the password first",
          skipToHomeBTN: "skip to home",
      signUpTitle: "Sign Up",
      signUpTitleName: "Enter Your Full Name",
      signUpTextName1: "First",
      signUpTextName2: "Middle",
      signUpTextName3: "Last",
      signUpTitlePhone: "Enter Your Phone Number",
      signUpTextPhone: "123-4567-8",
      signUpTextPhoneKey:"+974",
      signUpTitleEmail: "Enter Your Email",
      signUpTextEmail: "example@example.com",
      signUpTitlePass: "Enter Your Password",
      signUpTitleConfirmPass: "Confirm Your Password",
      signUpBTN: "Sign Up",
      signUpText1: "Already have an account?",
      signUpText2: "Sign In",
           errorKey: "An error occurred",
           signInProfile: "Login",
      signUpProfile: "Create Account",
          signInTitle:  "Sign In",
      signInText1:  "Hello",
      signInText2: "Sign into your account",
      signInTextEmail: "Email",
      signInTextPass: "Password",
      signInTextForgetPass: "Forget Your Password",
      signInTextBTN: "Login",
          readAppPolicyAndTerms: "I have read and agree to",
      privacyPolicy: "privacy policy",
      termsAndCondition: "Terms and conditions",
      and:" and ",
      signInBTN:"Login",
      languageWelcomeBTN:"اللغة العربية",
      drawerWidget1:"Home",
      drawerWidget2:"My Account",
      drawerWidget3:"Al-Radawi Modern School",
      drawerWidget4:"All Schools",
      drawerWidget5:"Settings",
      drawerWidget6:"Register a new school",
      drawerWidget7:"Application Management",
      drawerWidget8:"Terms of Use",
      drawerWidget9:"Privacy Policy",
      rememberMeKey:"Remember Me",
      chooseUserKey:"Choose user type",
      userType1: 'Parent',
      userType2: 'teacher',
      userType3: 'student',
      userType4: 'admin',
      userType5:'driver',
      textOfOTPTextField: 'Enter the code sent to you',
      textOfOTPBTNGoBack:"Return to the previous page",
      textOfOTPBTN:"Verify",
  otpAlert: "The code sent does not match the code entered. Please check WhatsApp.",
      signInAlert:"You must select a user type",
      signUpAlert1:"You must agree to the privacy policy, terms and conditions",
      signUpAlert2:"You must enter the mobile number to verify whether it is registered in a school or not.",
      detectPhoneNumberBTN:"Check Number",
      detectPhoneNumberText:"The phone number must be registered with the school",
      completeUserDataBTN:"Complete Account Information",
      completeUserDataText1:"Hello",
      completeUserDataText2:"Account Type:",
      parentTap1:"Absence Report",
      parentTap2:"Academic and Behavioral Recommendations",
      parentTap3:"Class Schedule",
      parentTap4:"Driver",
      parentTap5:"Teachers",
      parentTap6:"Posts",
      parentTap7 :"Messages",
      receivedKey: "Receive",
      senderKey: "Connect",
      showLocSchoolKey: "Show school location",
      schoolDetailsTap1:"School Information",
      schoolDetailsTap2: "Evaluations and Inquiries",
      schoolDetailsText1:"Information about the school:",
      schoolDetailsText2:"Site about the school:",
      schoolDetailsText3:"Open the school website",
      schoolDetailsText4:"Communicating with the school",
      replyKey:"reply",
      showDetailsKey:"show details",
      schoolLocationKey:'This is the school location',
      schoolSearchErrorKey:"Cannot search on empty name",
      sendingKidErrorKey:"The student can only be delivered when you are close to the school",
      receivingKidErrorKey: "The student can only be received when you are close to the school.",
      day1Key: "Sunday",
      day2Key: "Monday",
      day3Key: "Tuesday",
      day4Key: "Wednesday",
      day5Key: "Thursday",
      typeOfRecommendations:"Select the type of recommendation",
      typeOfRecommendation1:"Behavioral recommendations",
      typeOfRecommendation2:"Academic recommendations",
      choosePostType: "Choose post type",
      postType1: "Text",
      postType2: "Video",
      postType3: "Images",
      postType4: "pdf file",

    },
    "ar": {
      greetingWord:"اهلا وسهلا بك",
      requiredFiled:"هذه الخانة مطلوبه",
      invalidEmail:"هذا البريد الإلكتروني غير صالح",
      invalidPassword:"كلمة السر هذه غير صالحة",
      tryAgain:"الرجاء معاودة المحاولة في وقت لاحق",
      noInternet:"لا يوجد اتصال بالإنترنت",
      openInternet:"الرجاء فتح الإنترنت الخاص بك وحاول مرة أخرى",
      skipToHomeBTN: "انتقل إلى الصفحة الرئيسية" ,
      error:"حدث خطأ ، يرجى المحاولة مرة أخرى لاحقًا",
      phoneNumberError:"رقم التلفون هذا غير صالح",
      invalidReTypePassword:"كلمه السر غير متطابقة",
      enterPasswordFirst:"يجب إدخال كلمه السر اولآ",
      signUpTitle: "تسجيل حساب" ,
      signUpTitleName: "أدخل اسمك الكامل" ,
      signUpTextName1: "الأول" ,
      signUpTextName2: "الأوسط" ,
      signUpTextName3: "الأخير" ,
      signUpTitlePhone: "أدخل رقم هاتفك" ,
      signUpTextPhone: "123-4567-8" ,
      signUpTextPhoneKey: "974+" ,
      signUpTitleEmail: "أدخل بريدك الإلكتروني" ,
      signUpTextEmail: "example@example.com" ,
      signUpTitlePass: "أدخل كلمة المرور الخاصة بك" ,
      signUpTitleConfirmPass: "تأكيد كلمة المرور الخاصة بك" ,
      signUpBTN: "تسجيل",
      signUpText1: "هل لديك حساب بالفعل؟",
      signUpText2: "تسجيل الدخول" ,
           errorKey:"حدث خطأ",
            signInProfile: "تسجيل الدخول",
      signUpProfile:  "إنشاء حساب",
      signInTitle: "تسجيل الدخول" ,
      signInText1: "مرحبًا" ,
      signInText2: "تسجيل الدخول إلى حسابك" ,
      signInTextEmail: "البريد الإلكتروني" ,
      signInTextPass: "كلمة المرور" ,
      signInTextForgetPass: "نسيت كلمة المرور" ,
      signInTextBTN: "تسجيل الدخول" ,
      readAppPolicyAndTerms: "أنا قرأت وأوافق على",
      privacyPolicy: "سياسة خاصة",
      termsAndCondition: "أحكام وشروط",
      and:" و ",
      signInBTN: "تسجيل الدخول",
      languageWelcomeBTN:"english",
      drawerWidget1:"الرئيسية",
      drawerWidget2:"حسابي",
      drawerWidget3:"مدرسة الرضوي الحديثة",
      drawerWidget4:"كل المدارس",
      drawerWidget5:"الإعدادات",
      drawerWidget6:"تسجيل مدرسة جديدة",
      drawerWidget7:"إدارة التطبيق",
      drawerWidget8:"شروط الإستخدام",
      drawerWidget9:"سياسة الخصوصية",
      rememberMeKey:"تذكرنى",
      chooseUserKey:"اختر نوع المستخدم",
   userType1:   'ولي أمر',
   userType2: 'مدرس',
   userType3: 'طالب',
   userType4:  'مشرف',
   userType5:'سائق',
      textOfOTPTextField: 'أدخال الكود المرسل أليك',
      textOfOTPBTNGoBack:"العوده ألى الصفحه السابقه",
      textOfOTPBTN:"تحقق",
      otpAlert:"الكود المرسل غير مطابق الكود الذى تم إدخاله يرجى مراجعه الواتس اب",
      signInAlert:"يجب أختيار نوع مستخدم",
      signUpAlert1:"يجب الموافقه على سياسه خاصه والأحكام و الشروط",
      signUpAlert2:"يجب أدخال رقم الجوال للتحقق من أنه تم تسجيله فى مدرسه أم لا",
      detectPhoneNumberBTN:"تحقق من الرقم",
      detectPhoneNumberText:"يجب ان يكون رقم الهاتف مسجل فى المدرسه",
      completeUserDataBTN:"أستكمال بينات الحساب",
      completeUserDataText1:"مرحبا",
      completeUserDataText2:"نوع الحساب :",
      parentTap1:"تقرير الغياب",
      parentTap2:"التوصيات الأكاديمية والسلوكية",
      parentTap3:"الجدول الدراسي",
      parentTap4:"السائق",
      parentTap5:"المدرسين",
      parentTap6 :"المنشورات",
      parentTap7 :"لرسائل",
   receivedKey: "استلام",
   senderKey: "توصيل",
   showLocSchoolKey: "إظهار موقع المدرسه",
      showDetailsKey:"عرض تفاصيل",
      schoolDetailsTap1:"معلومات المدرسه",
      schoolDetailsTap2: "تقيمات و استفسرات",
      schoolDetailsText1:"معلومات عن المدرسه:",
      schoolDetailsText2:"موقع عن المدرسه:",
      schoolDetailsText3:"فتح موقع المدرسه",
      schoolDetailsText4:"التواصل مع المدرسه",
      replyKey:"الرد",
      schoolLocationKey:'هذا هو موقع المدرسه',
      schoolSearchErrorKey:"لا يمكن البحث على اسم فارغ",
      sendingKidErrorKey:"لا يمكن توصيل الطالب ألا عندما تكون قريب من المدرسه",
      receivingKidErrorKey: "لا يمكن أستلام الطالب ألا عندما تكون قريب من المدرسه",
      day1Key: "الأحد",
      day2Key: "الأثنين",
      day3Key: "الثلاثاء",
      day4Key: "الأربعاء",
      day5Key: "الخميس",
      typeOfRecommendations:"أختر نوع التوصيه",
      typeOfRecommendation1:"توصيات سلوكيه",
      typeOfRecommendation2:"توصيات أكادميه",
   choosePostType: "أختر نوع المنشور",
   postType1: "نص",
   postType2: "فيديو",
   postType3: "صور",
   postType4: "ملف pdf",

    }
  };
}